# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180510_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency code on the site (for example, USD, GBR, UAH etc.). Default USD', max_length=3, verbose_name='Currency'),
        ),
    ]
