# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_auto_20180510_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(blank=True, help_text='Currency code on the site (for example, USD, GBR, UAH etc.). Default USD', max_length=3, verbose_name='Currency')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.SiteConfiguration')),
            ],
        ),
    ]
